// Generated by Xata Codegen 0.26.7. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "items",
    columns: [
      {
        name: "product",
        type: "link",
        link: { table: "products" },
        unique: true,
      },
      { name: "amount", type: "float" },
      { name: "comment", type: "text" },
      { name: "unit", type: "link", link: { table: "units" } },
      { name: "status", type: "string", notNull: true, defaultValue: "ACTIVE" },
      { name: "list", type: "link", link: { table: "lists" } },
    ],
  },
  {
    name: "units",
    columns: [{ name: "name", type: "string", unique: true }],
    revLinks: [{ column: "unit", table: "items" }],
  },
  {
    name: "products",
    columns: [
      { name: "name", type: "string" },
      { name: "productType", type: "string" },
    ],
    revLinks: [{ column: "product", table: "items" }],
  },
  {
    name: "lists",
    columns: [
      {
        name: "name",
        type: "string",
        notNull: true,
        defaultValue: "Shopping List",
      },
      { name: "status", type: "string", notNull: true, defaultValue: "ACTIVE" },
      { name: "user", type: "string" },
    ],
    revLinks: [{ column: "list", table: "items" }],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Items = InferredTypes["items"];
export type ItemsRecord = Items & XataRecord;

export type Units = InferredTypes["units"];
export type UnitsRecord = Units & XataRecord;

export type Products = InferredTypes["products"];
export type ProductsRecord = Products & XataRecord;

export type Lists = InferredTypes["lists"];
export type ListsRecord = Lists & XataRecord;

export type DatabaseSchema = {
  items: ItemsRecord;
  units: UnitsRecord;
  products: ProductsRecord;
  lists: ListsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Hendrik-s-workspace-0545qt.eu-central-1.xata.sh/db/shopping-list",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
